# Generated by Django 4.0.4 on 2022-05-01 01:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=1000)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
    ]
